### PR TITLE
docs: migration to twitch4j.github.io

### PR DESCRIPTION
**Pull request by stachu540**
### Prerequisites for Code Changes
* [x] This pull request follows the code style of the project
* [x] I have tested this feature

### Changes Proposed
* Planned migration to https://twitch4j.github.io with better lookup

### Additional Information 
Documentation migration has been completed. Only documentation in `develop`/`master` branch is leftover before `v1.2.0` - I think I have done in time, maybe before deadline (which not exist yet 😄).

Closing #225

### CODE REVIEW

**Comment by stachu540** [comment]
Cause #220 are violate migration, files in this PR will be removed and must be updated into `twitch4/twitch4j.github.io` repository after migration.

**Review by PhilippHeuer — CHANGES_REQUESTED** [review]
Can you also update the link to the new documentation page ìn the `README.md`?

**Comment by stachu540** [comment]
Up you go. Also I made logo linked into main page.

**Comment by stachu540** [comment]
Cannot resolve this conflicts after #220

**Review by PhilippHeuer — APPROVED** [review]

**Pull request merged**
